kind: Deployment
apiVersion: apps/v1
metadata:
  name: &app "netmaker-dns" ############## VAR
  labels:
    app: *app
    part-of: &part-of "netmaker" ############# VAR
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: *app
      part-of: *part-of
  template:
    metadata:
      labels:
        app: *app
        part-of: *part-of
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: *app
        image: coredns/coredns
        args:
        - -conf
        - /root/dnsconfig/Corefile
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        volumeMounts:
        - name: *part-of
          mountPath: /root/dnsconfig
          readOnly: true
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 127.0.0.1
      volumes:
      - name: *part-of
        persistentVolumeClaim:
          claimName: *part-of
