---
apiVersion: v1
kind: Service
metadata:
  labels: &labels
    app: netmaker-dns
    part-of: netmaker
  name: netmaker-dns
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  selector: *labels
  sessionAffinity: None
  type: ClusterIP
